MONGO:
  URI:
    ENABLED: false
    CONNECTION-STRING: ""
  DEFAULT:
    HOST: "localhost"
    PORT: 27017
    DATABASE: "Clubs"
    AUTHENTICATION:
      ENABLED: false
      USERNAME: ""
      PASSWORD: ""

REDIS:
  HOST: "127.0.0.1"
  PORT: 6379
  CHANNEL: "Clubs"
  PASSWORD: ""